import type { PresetTheme } from "./types";

export const presetThemes: readonly PresetTheme[] = [
  {
    configuration: {
      background: { kind: "preset", preset: "clean-light" },
      bodyHeadingAlignment: "center",
      bodyHeadingSize: "medium",
      contentSurface: "none",
      coverLayout: "center-poster",
      decorationColor: "#64748b",
      density: "balanced",
      fontId: "sans",
      headingDecoration: "none",
    },
    description: "简洁明亮的白色主题，带柔和光影",
    id: "clean-light",
    name: "清新白",
  },
  {
    configuration: {
      background: { kind: "preset", preset: "trianglify-gray" },
      bodyHeadingAlignment: "left",
      bodyHeadingSize: "large",
      contentSurface: "floating-card",
      coverLayout: "top-left",
      decorationColor: "#334155",
      density: "compact",
      fontId: "sans",
      headingDecoration: "underline",
    },
    description: "抽象三角形为背景的极简风格",
    id: "trianglify-minimalist",
    name: "三角极简",
  },
  {
    configuration: {
      background: { kind: "preset", preset: "night-aurora" },
      bodyHeadingAlignment: "left",
      bodyHeadingSize: "medium",
      contentSurface: "none",
      coverLayout: "bottom-left",
      decorationColor: "#a78bfa",
      density: "balanced",
      fontId: "sans",
      headingDecoration: "underline",
    },
    description: "深邃墨色配紫蓝极光，沉静而有呼吸感",
    id: "clean-dark",
    name: "墨夜极光",
  },
  {
    configuration: {
      background: { kind: "preset", preset: "warm-sun" },
      bodyHeadingAlignment: "center",
      bodyHeadingSize: "large",
      contentSurface: "floating-card",
      coverLayout: "center-poster",
      decorationColor: "#f4b76a",
      density: "balanced",
      fontId: "sans",
      headingDecoration: "highlight",
    },
    description: "奶油蜜桃光晕，温柔包裹的午后阳光",
    id: "gradient-warm",
    name: "蜜光暖阳",
  },
  {
    configuration: {
      background: { kind: "preset", preset: "cool-mist" },
      bodyHeadingAlignment: "center",
      bodyHeadingSize: "medium",
      contentSurface: "none",
      coverLayout: "center-poster",
      decorationColor: "#1a3556",
      density: "balanced",
      fontId: "serif",
      headingDecoration: "none",
    },
    description: "雾蓝与薰衣草交织，清晨薄雾的清雅微光",
    id: "gradient-cool",
    name: "晨雾微光",
  },
  {
    configuration: {
      background: { kind: "preset", preset: "cherry-cream" },
      bodyHeadingAlignment: "center",
      bodyHeadingSize: "medium",
      contentSurface: "none",
      coverLayout: "center-poster",
      decorationColor: "#b42355",
      density: "balanced",
      fontId: "sans",
      headingDecoration: "wavy",
    },
    description: "蜜桃粉与奶油白交融，奶霜质感的温柔粉调",
    id: "xiaohongshu-pink",
    name: "樱花奶霜",
  },
  {
    configuration: {
      background: { color: "#fefcf3", kind: "solid" },
      bodyHeadingAlignment: "left",
      bodyHeadingSize: "medium",
      contentSurface: "none",
      coverLayout: "top-left",
      decorationColor: "#44403c",
      density: "balanced",
      fontId: "serif",
      headingDecoration: "none",
    },
    description: "护眼米色，舒适阅读",
    id: "reading-mode",
    name: "阅读模式",
  },
  {
    configuration: {
      background: { color: "#fbfbfb", kind: "solid" },
      bodyHeadingAlignment: "left",
      bodyHeadingSize: "medium",
      contentSurface: "notebook",
      coverLayout: "top-left",
      decorationColor: "#1d1d1f",
      density: "compact",
      fontId: "sans",
      headingDecoration: "none",
    },
    description: "简洁的苹果备忘录风格",
    id: "apple-notes",
    name: "Apple 备忘录",
  },
];

export const getThemeById = (id: string): PresetTheme | undefined =>
  presetThemes.find((theme) => theme.id === id);

export const defaultTheme = presetThemes[0];
